In [12]:
import numpy as np
from scipy.spatial.distance import cdist

In [20]:
dim = 3
n = 3

r = np.array([1, 1, 1, 2, 3, 2, 0, 1, 0])
v = np.array([0, 1.5, 4, 2, 1, 1, 1, 0, 1])

In [21]:
rr = r.reshape((n, dim))
rr

array([[1, 1, 1],
       [2, 3, 2],
       [0, 1, 0]])

In [27]:
dists = cdist(rr, rr)
dists += np.diag(np.ones(n))
dists

array([[1.        , 2.44948974, 1.41421356],
       [2.44948974, 1.        , 3.46410162],
       [1.41421356, 3.46410162, 1.        ]])

In [23]:
m = np.random.random(n)
m

array([0.71313865, 0.56860743, 0.46508314])

In [28]:
rr

array([[1, 1, 1],
       [2, 3, 2],
       [0, 1, 0]])

In [29]:
rr[:, None, :]

array([[[1, 1, 1]],

       [[2, 3, 2]],

       [[0, 1, 0]]])

In [31]:
rr[None, :, :]

array([[[1, 1, 1],
        [2, 3, 2],
        [0, 1, 0]]])

In [32]:
deltas = rr[:, None, :] - rr[None, :, :]

In [89]:
deltas[0, 1]

array([-1, -2, -1])

In [90]:
rr[1] - rr[0]

array([1, 2, 1])

In [88]:
(deltas * m[:, None]).sum(axis=1).flatten()

array([-0.1035243 , -1.13721487, -0.1035243 ,  1.64330493,  2.35644358,
        1.64330493, -1.85035352, -1.13721487, -1.85035352])

In [67]:
deltas[0, 1] * m[1] + deltas[0, 2] * m[2]

array([-0.1035243 , -1.13721487, -0.1035243 ])

In [91]:
dists = np.linalg.norm(deltas, axis=2)
dists

array([[0.        , 2.44948974, 1.41421356],
       [2.44948974, 0.        , 3.46410162],
       [1.41421356, 3.46410162, 0.        ]])

In [95]:
dists[:, :, None][0, 1]

array([2.44948974])